# Generated by Django 3.2.11 on 2022-02-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='title',
            new_name='nachname',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='image',
            new_name='redenanzahl',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='technology',
            new_name='rolle_lang',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='description',
            new_name='vorname',
        ),
    ]
