# Generated by Django 3.2.11 on 2022-02-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220202_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='img_path_profil',
            field=models.FilePathField(default=' ', path='/img'),
            preserve_default=False,
        ),
    ]
