# Generated by Django 3.2.11 on 2022-01-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plenarprotokoll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='plenarprotokoll',
        ),
    ]
