# Generated by Django 3.2.11 on 2022-01-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenarprotokoll', '0003_auto_20220118_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plenarprotokoll',
            name='image',
        ),
        migrations.AlterField(
            model_name='plenarprotokoll',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plenarprotokoll',
            name='redner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plenarprotokoll',
            name='vorname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
