# Generated by Django 3.2.11 on 2022-01-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plenarprotokoll', '0004_auto_20220118_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plenarprotokoll',
            old_name='name',
            new_name='nachname',
        ),
        migrations.RemoveField(
            model_name='plenarprotokoll',
            name='vorname',
        ),
    ]
