# Generated by Django 3.2.11 on 2022-01-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenarprotokoll', '0006_auto_20220122_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metaprotokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ort', models.TextField(blank=True, null=True)),
                ('datum', models.TextField(blank=True, null=True)),
                ('wahlperiode', models.TextField(blank=True, null=True)),
                ('sitzungsnr', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meta',
            },
        ),
    ]
