# Generated by Django 3.2.11 on 2022-02-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenarprotokoll', '0007_metaprotokoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaprotokoll',
            name='path',
            field=models.FilePathField(default='', path='/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metaprotokoll',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
